[purescript]
directory = "purescript"
package = "integration-digitalocean"
main = "Infra.Main"

[lean]
directory = "lean/integration-digitalocean"
main = "infra"
core = { path = "lean" }

[providers.digitalocean]
source = "digitalocean/digitalocean"
version = "2.100.0"
module_root = "DigitalOcean"

[workspace]
directory = ".inframe"
graph_directory = ".inframe/graphs"

[stacks.smoke.backend]
type = "local"

[stacks.example]
frontend = "purescript"
main = "Infra.Platform"
test = "Infra.PlatformTest"

[stacks.example.backend]
type = "local"

[stacks.lean-example]
frontend = "lean"
main = "platform"
test = "platform-test"

[stacks.lean-example.backend]
type = "local"
