[package]
name = "inframe-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "inframe"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
inframe-binding-model = { path = "../binding-model" }
inframe-emit-purescript = { path = "../emit-purescript" }
inframe-graph-ir = { path = "../graph-ir" }
inframe-opentofu = { path = "../opentofu" }
inframe-provider-schema = { path = "../provider-schema" }

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
tempfile.workspace = true

[lints]
workspace = true
